### ISSUE TITLE
Feature request: HOTP counter field

### ISSUE THREAD

**Issue by SievaFliesAlone** [matteo-convertino/otpmanager-nextcloud#56]
When importing an old HOTP key, there's no way to set (or change) the counter, which is critical for HOTP.

**Comment by matteo-convertino** [comment]
This should be fixed in version [1.0.4](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v1.0.4) 🚀.
If I’ve understood correctly, you were referring to when the accounts are imported.

[EDIT]
Or perhaps you meant when creating the account?

**Comment by SievaFliesAlone** [comment]
It's not fixed.

When adding or editing an HOTP “account”, there is no “Counter” field.

<img width="445" height="535" alt="Image" src="https://github.com/user-attachments/assets/0cb2b126-1bee-4372-9b03-b18c711aa665" />

v1.0.4

UPD: if user has a pre-existing HOTP key, it's impossible to add it via the UI because there's no counter field — this is only possible only via an import. It's unobvious and required reverse-engineering.

**Comment by matteo-convertino** [comment]
Ok, perfect so it’s during creation/editing. Yes, with this release I’d actually sorted it out during import instead.

I’ve already added the button and tested it; I’ll release the new version tomorrow.

<img width="470" height="550" alt="Image" src="https://github.com/user-attachments/assets/2dcd9373-1868-4080-a618-afe2eba7757f" />

[EDIT]
I’ll most likely include it in the next version of the mobile app as well.

**Comment by SievaFliesAlone** [comment]
Thank you!

**Comment by matteo-convertino** [comment]
Version [1.0.5](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v1.0.5) has been released. For the time being, I have made it possible to set this field only at the time of creation. I feel this is sensitive data not to be edited 🤔.
